import type { Promotion } from "@/lib/supabase";

export const platformMeta: Record<string, { color: string; bg: string; textColor: string; appUrl: string; webUrl: string }> = {
  GrabFood: {
    color: "#00B14F",
    bg: "#f0fdf4",
    textColor: "#166534",
    appUrl: "grab://food",
    webUrl: "https://food.grab.com/th/en/",
  },
  "LINE MAN": {
    color: "#00C300",
    bg: "#f0fdf9",
    textColor: "#065f46",
    appUrl: "https://liff.line.me/1654046602-oR3JNKQ1",
    webUrl: "https://lineman.line.me/",
  },
  ShopeeFood: {
    color: "#EE4D2D",
    bg: "#fff1ee",
    textColor: "#9a3412",
    appUrl: "shopeefood://",
    webUrl: "https://shopee.co.th/m/shopeefood",
  },
  Robinhood: {
    color: "#4A148C",
    bg: "#faf5ff",
    textColor: "#6b21a8",
    appUrl: "robinhood://",
    webUrl: "https://www.robinhood.co.th/",
  },
};

export const fallbackPromotions: Promotion[] = [
  {
    id: "1",
    platform: "GrabFood",
    campaign_name: "KBank Credit Card Privileges",
    promo_code: "KBANKGF",
    conditions: "ส่วนลด ฿80 เมื่อสั่งขั้นต่ำ ฿500 ชำระผ่านบัตรเครดิต KBank",
    reference_link: "https://food.grab.com/th/en/",
    fetched_at: new Date().toISOString(),
    is_active: true,
  },
  {
    id: "2",
    platform: "GrabFood",
    campaign_name: "GrabFood x Krungsri First Choice",
    promo_code: "KFV50",
    conditions: "ส่วนลด ฿50 สั่งขั้นต่ำ ฿300 ชำระผ่านบัตรกรุงศรีเฟิร์สช้อยส์",
    reference_link: "https://food.grab.com/th/en/",
    fetched_at: new Date().toISOString(),
    is_active: true,
  },
  {
    id: "3",
    platform: "LINE MAN",
    campaign_name: "LINE MAN x KTC VISA",
    promo_code: "KTCVSPD80",
    conditions: "ส่วนลด ฿80 ชำระผ่านบัตรเครดิต KTC VISA",
    reference_link: "https://lineman.line.me/",
    fetched_at: new Date().toISOString(),
    is_active: true,
  },
  {
    id: "4",
    platform: "LINE MAN",
    campaign_name: "LINE MAN x GSB Debit Card",
    promo_code: "GSBDB50",
    conditions: "ส่วนลด ฿50 สั่งขั้นต่ำ ฿150 สำหรับผู้ถือบัตรเดบิตธนาคารออมสิน",
    reference_link: "https://lineman.line.me/",
    fetched_at: new Date().toISOString(),
    is_active: true,
  },
  {
    id: "5",
    platform: "ShopeeFood",
    campaign_name: "Shopee Double Sale",
    promo_code: "เก็บคูปองในแอป",
    conditions: "ส่วนลดสูงสุด 50% สำหรับร้านที่ร่วมรายการ และโค้ดส่งฟรี",
    reference_link: "https://shopee.co.th/m/shopeefood",
    fetched_at: new Date().toISOString(),
    is_active: true,
  },
  {
    id: "6",
    platform: "Robinhood",
    campaign_name: "Robinhood 50% Flash Sale",
    promo_code: "ลดอัตโนมัติ ไม่ต้องใช้รหัส",
    conditions: "ส่วนลดสูงสุด 50% เฉพาะร้านและเมนูที่ร่วมรายการ ไม่กำหนดขั้นต่ำ",
    reference_link: "https://www.robinhood.co.th/",
    fetched_at: new Date().toISOString(),
    is_active: true,
  },
];

export const fallbackRestaurants = [
  {
    id: "r1",
    name: "กะเพราตาแป๊ะ",
    category: "อาหารไทย",
    image_url: "https://images.pexels.com/photos/1640777/pexels-photo-1640777.jpeg?auto=compress&cs=tinysrgb&w=400&h=300&fit=crop",
    line_oa_url: "https://line.me/ti/p/@mrhavefood",
    description: "กะเพราหมูกรอบเทพ การันตีความอร่อย สั่งตรงจากร้าน ไม่เสียค่า GP",
    is_active: true,
    created_at: new Date().toISOString(),
  },
  {
    id: "r2",
    name: "ข้าวมันไก่ต้นตำรับ",
    category: "อาหารจีน",
    image_url: "https://images.pexels.com/photos/1279330/pexels-photo-1279330.jpeg?auto=compress&cs=tinysrgb&w=400&h=300&fit=crop",
    line_oa_url: "https://line.me/ti/p/@mrhavefood",
    description: "ข้าวมันไก่ต้นตำรับสูตรโบราณ น้ำซุปใสหวาน ราคาหน้าร้าน ไม่บวก GP",
    is_active: true,
    created_at: new Date().toISOString(),
  },
  {
    id: "r3",
    name: "ยำแซ่บซอย",
    category: "อาหารอีสาน",
    image_url: "https://images.pexels.com/photos/2673353/pexels-photo-2673353.jpeg?auto=compress&cs=tinysrgb&w=400&h=300&fit=crop",
    line_oa_url: "https://line.me/ti/p/@mrhavefood",
    description: "ยำตำรับอีสานแท้ รสแซ่บเผ็ดร้อน สั่งผ่าน LINE ได้เลย ไม่มีค่าธรรมเนียม",
    is_active: true,
    created_at: new Date().toISOString(),
  },
];
