import type { Promotion } from "@/lib/supabase";

export const platformMeta: Record<string, { color: string; bg: string; textColor: string; appUrl: string; webUrl: string }> = {
  GrabFood: {
    color: "#00B14F",
    bg: "#f0fdf4",
    textColor: "#166534",
    appUrl: "grab://food",
    webUrl: "https://food.grab.com/th/en/",
  },
  "LINE MAN": {
    color: "#00C300",
    bg: "#f0fdf9",
    textColor: "#065f46",
    appUrl: "https://liff.line.me/1654046602-oR3JNKQ1",
    webUrl: "https://lineman.line.me/",
  },
  ShopeeFood: {
    color: "#EE4D2D",
    bg: "#fff1ee",
    textColor: "#9a3412",
    appUrl: "shopeefood://",
    webUrl: "https://shopee.co.th/m/shopeefood",
  },
  Robinhood: {
    color: "#4A148C",
    bg: "#faf5ff",
    textColor: "#6b21a8",
    appUrl: "robinhood://",
    webUrl: "https://www.robinhood.co.th/",
  },
};

export const fallbackPromotions: Promotion[] = [
  {
    id: "1",
    platform: "GrabFood",
    campaign_name: "GSB Debit Card Exclusive",
    promo_code: "GSB100",
    conditions: "สั่งขั้นต่ำ 300 บาท, ชำระผ่าน GrabPay ด้วยบัตรเดบิต GSB, จำกัด 2 สิทธิ์/คน/เดือน",
    start_date: "2026-01-01",
    end_date: "2026-12-31",
    reference_link: "https://www.grab.com/th/en/blog/gsb_y2026/",
    fetched_at: new Date().toISOString(),
    is_active: true,
  },
  {
    id: "2",
    platform: "GrabFood",
    campaign_name: "KBank Credit Card Promotion",
    promo_code: "KBANKGF",
    conditions: "สั่งขั้นต่ำ 500 บาท, ชำระผ่าน GrabPay ด้วยบัตรเครดิต KBank ที่ร่วมรายการ, จำกัด 1 สิทธิ์/คน/เดือน",
    start_date: "2026-03-01",
    end_date: "2027-02-28",
    reference_link: "https://www.grab.com/th/en/blog/kbankgf_2026/",
    fetched_at: new Date().toISOString(),
    is_active: true,
  },
  {
    id: "3",
    platform: "LINE MAN",
    campaign_name: "KTC VISA Foodie",
    promo_code: "KTCVSPD80",
    conditions: "สั่งขั้นต่ำ 450 บาท (เฉพาะค่าอาหาร), ชำระผ่านบัตรเครดิต KTC VISA เท่านั้น",
    start_date: "2026-02-01",
    end_date: "2026-07-31",
    reference_link: "https://lineman.line.me/partnership-ktc/",
    fetched_at: new Date().toISOString(),
    is_active: true,
  },
  {
    id: "4",
    platform: "LINE MAN",
    campaign_name: "Rabbit Rewards Special",
    promo_code: "ต้องแลกรับรหัสผ่านแอป Rabbit Rewards",
    conditions: "สั่งขั้นต่ำ 200 บาท, ใช้ได้เฉพาะร้านที่ร่วมรายการ (GP), จำกัด 1 รหัส/สิทธิ์",
    start_date: "2025-09-16",
    end_date: "2026-03-31",
    reference_link: "https://rewards.rabbit.co.th/rewards/line-man---get-150-thb-discount-on-food-delivery-order-with-min-spend-at-200-thb-batch-sep25",
    fetched_at: new Date().toISOString(),
    is_active: true,
  },
  {
    id: "5",
    platform: "LINE MAN",
    campaign_name: "LINE MAN MART x Big C",
    promo_code: "BIGC200",
    conditions: "ช้อปขั้นต่ำ 800 บาท ที่ Big C ผ่านบริการ LINE MAN MART",
    start_date: "2026-03-01",
    end_date: "2026-03-31",
    reference_link: "https://lineman.line.me/how-to-apply-promo-code-2/",
    fetched_at: new Date().toISOString(),
    is_active: true,
  },
  {
    id: "6",
    platform: "ShopeeFood",
    campaign_name: "ShopeeFood x KFC New User",
    promo_code: "เก็บคูปองในแอป",
    conditions: "เฉพาะลูกค้าใหม่, ไม่มีขั้นต่ำ, ใช้ได้กับเมนูที่ร่วมรายการ",
    start_date: null,
    end_date: null,
    reference_link: "https://promotion.thairath.co.th/shopee-food-coupons/",
    fetched_at: new Date().toISOString(),
    is_active: true,
  },
  {
    id: "7",
    platform: "ShopeeFood",
    campaign_name: "ShopeeFood x McDonald's",
    promo_code: null,
    conditions: "สำหรับทุกผู้ใช้, เฉพาะเมนูเซ็ตที่ร่วมรายการ, ไม่มีขั้นต่ำ",
    start_date: null,
    end_date: null,
    reference_link: "https://promotion.thairath.co.th/shopee-food-coupons/",
    fetched_at: new Date().toISOString(),
    is_active: true,
  },
  {
    id: "8",
    platform: "Robinhood",
    campaign_name: "Robinhood Food (Current Status)",
    promo_code: null,
    conditions: "ตรวจสอบราคาพิเศษได้ที่หน้าแอปพลิเคชันในส่วน 'ดีลดีร้านดัง'",
    start_date: "2026-03-01",
    end_date: "2026-03-31",
    reference_link: "https://www.robinhood.co.th/",
    fetched_at: new Date().toISOString(),
    is_active: true,
  },
];

export const fallbackRestaurants = [
  {
    id: "r1",
    name: "กะเพราตาแป๊ะ",
    category: "อาหารไทย",
    image_url: "https://images.pexels.com/photos/1640777/pexels-photo-1640777.jpeg?auto=compress&cs=tinysrgb&w=400&h=300&fit=crop",
    line_oa_url: "https://line.me/ti/p/@mrhavefood",
    description: "กะเพราหมูกรอบเทพ การันตีความอร่อย สั่งตรงจากร้าน ไม่เสียค่า GP",
    is_active: true,
    created_at: new Date().toISOString(),
  },
  {
    id: "r2",
    name: "ข้าวมันไก่ต้นตำรับ",
    category: "อาหารจีน",
    image_url: "https://images.pexels.com/photos/1279330/pexels-photo-1279330.jpeg?auto=compress&cs=tinysrgb&w=400&h=300&fit=crop",
    line_oa_url: "https://line.me/ti/p/@mrhavefood",
    description: "ข้าวมันไก่ต้นตำรับสูตรโบราณ น้ำซุปใสหวาน ราคาหน้าร้าน ไม่บวก GP",
    is_active: true,
    created_at: new Date().toISOString(),
  },
  {
    id: "r3",
    name: "ยำแซ่บซอย",
    category: "อาหารอีสาน",
    image_url: "https://images.pexels.com/photos/2673353/pexels-photo-2673353.jpeg?auto=compress&cs=tinysrgb&w=400&h=300&fit=crop",
    line_oa_url: "https://line.me/ti/p/@mrhavefood",
    description: "ยำตำรับอีสานแท้ รสแซ่บเผ็ดร้อน สั่งผ่าน LINE ได้เลย ไม่มีค่าธรรมเนียม",
    is_active: true,
    created_at: new Date().toISOString(),
  },
];
